# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db04805181f7fc36955dcc194c52fe3e99b800b23b4cc5d6104bf0d6ca7f276784d5051efea36fdbab61387fcfdad0ca935a3b229d1dd1d4e4b796fcf71a285f

test:
  secret_key_base: c8fc803ba4f01e4b1a0ab29910310e47f814238ae9375a71b1f666f55b6b16e442572f6c192986469a366eec1ddf0502c95b96f70f19545aa4777b442a5e9c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
